[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_PRODUCTION = "false"
  # Vite envs used by src/runtime-config.js
  # Set these in Netlify UI or via netlify.toml for non-sensitive client config
  # DO NOT add server-only secrets here
  VITE_SUPABASE_URL = "https://id.kkarlsen.dev"
  VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_z9EoG7GZZMS3RL4hmilh5A_xI0va5Nb"
  # Optional: override API base (defaults to "/api")
  # VITE_API_BASE = "/api"

[[redirects]]
  # Proxy API requests to Azure backend
  from = "/api/*"
  to = "https://wageapp-prod.azurewebsites.net/:splat"
  status = 200
  force = true

[[redirects]]
  # Serve login page as-is (avoid SPA fallback)
  from = "/kalkulator/login.html"
  to = "/kalkulator/login.html"
  status = 200

[[redirects]]
  # Kalkulator SPA fallback
  from = "/kalkulator/*"
  to = "/kalkulator/index.html"
  status = 200

[[redirects]]
  # Root SPA fallback (landing page)
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # Old auth routes
  from = "/auth.html"
  to = "/kalkulator/index.html"
  status = 301

[[redirects]]
  from = "/kalkulator/auth.html"
  to = "/kalkulator/index.html"
  status = 301

# Security headers
[[headers]]
  # Apply to all routes (static files, SPA routes, and proxied API)
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; object-src 'none'; form-action 'self'; upgrade-insecure-requests; script-src 'self' https://cdn.jsdelivr.net https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com https://cdnjs.cloudflare.com; img-src 'self' data: blob: https://id.kkarlsen.dev; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com data:; connect-src 'self' https://id.kkarlsen.dev wss://id.kkarlsen.dev;"
    X-Frame-Options = "DENY"
