[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/api/*"
  to = "https://wageapp-prod.azurewebsites.net/:splat"
  status = 200
  force = true