############################################################
# Netlify config for MARKETING site (monorepo root)
# - App lives on its own domain/subsite (no /kalkulator path)
# - Keep simple SPA fallback and redirect legacy /kalkulator to app domain
############################################################


[[redirects]]
  # Redirect any old /kalkulator paths to the dedicated app domain
  from = "/kalkulator/*"
  to = "https://kalkulator.kkarlsen.dev/:splat"
  status = 301
  force = true

[[redirects]]
  # Root SPA fallback (landing page)
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; object-src 'none'; form-action 'self'; upgrade-insecure-requests; script-src 'self' 'nonce-abc123' https://cdn.jsdelivr.net https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com https://cdnjs.cloudflare.com; img-src 'self' data: blob: https://*.supabase.co https://lh3.googleusercontent.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com data:; connect-src 'self';"